"""rename address

Revision ID: f6e5e36400d2
Revises: ba54d8d79838
Create Date: 2025-04-01 11:35:47.926005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e5e36400d2'
down_revision = 'ba54d8d79838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the column from 'address' to 'location'
    op.alter_column('departments', 'address', new_column_name='location')
    # Change the nullable constraint to NOT NULL
    op.alter_column('departments', 'location', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the nullable constraint to NULL
    op.alter_column('departments', 'location', existing_type=sa.String(), nullable=True)
    # Rename the column back from 'location' to 'address'
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###